# 2024-02-10 21:50

name: Fork Filter lists

on:
  workflow_dispatch:
  schedule:
    - cron: "30 * * * *"
  
jobs:
  Fork-FLITER-list:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'
    
    steps: 
    - name: Checkout target repository
      uses: actions/checkout@v4.1.0
      with:
        repository: axtyet/Tool
        path: Tool-repo

######
      # 修改脚本链接
    - name: Edit iios/QuantumultX/chxm1023/advertising
      run: |
        cd iios-repo/QuantumultX/Chxm1023/Advertising
        for file in *.js; do
            if [ "$file" ] ; then
              sed -i 's/raw\.githubusercontent.com\/chxm1023\/Advertising\/main/raw.githubusercontent\.com\/axtyet\/iios\/main\/QuantumultX\/Chxm1023\/Advertising/g' "$file"
            else
              echo "$file not found."
            fi
          done
       # 修改脚本链接
    - name: Edit iios/QuantumultX/chxm1023/Rewrite
      run: |
        cd iios-repo/QuantumultX/Chxm1023/Rewrite
        for file in *.js; do
            if [ "$file" ] ; then
              sed -i 's/raw\.githubusercontent.com\/chxm1023\/Rewrite\/main/raw.githubusercontent\.com\/axtyet\/iios\/main\/QuantumultX\/Chxm1023\/Rewrite/g' "$file"
            else
              echo "$file not found."
            fi
          done     
       # 修改脚本链接    
    - name: Edit iios/QuantumultX/Chxm1023/rewrite/Revenuecat
      run: |
        cd iios-repo/QuantumultX/Chxm1023/Rewrite/Revenuecat
        for file in *.js; do
            if [ "$file" ] ; then
              sed -i 's/raw\.githubusercontent.com\/chxm1023\/Rewrite\/main\/Revenuecat/raw.githubusercontent\.com\/axtyet\/iios\/main\/QuantumultX\/Chxm1023\/Rewrite\/Revenuecat/g' "$file"
            else
              echo "$file not found."
            fi
          done
       # 修改脚本链接
    - name: Edit iios/QuantumultX/Chxm1023/rewrite/iTunes
      run: |
        cd iios-repo/QuantumultX/Chxm1023/Rewrite/iTunes
        for file in *.js; do
            if [ "$file" ] ; then
              sed -i 's/raw\.githubusercontent.com\/chxm1023\/Rewrite\/main\/iTunes/raw.githubusercontent\.com\/axtyet\/iios\/main\/QuantumultX\/Chxm1023\/Rewrite\/iTunes/g' "$file"
            else
              echo "$file not found."
            fi
          done
          # 修改脚本链接
      - name: Edit iios/QuantumultX/chxm1023/Script_X
        run: |
        cd iios-repo/QuantumultX/Chxm1023/Script_X
        for file in Collections.conf; do
            if [ "$file" ] ; then
              sed -i 's/raw\.githubusercontent.com\/chxm1023\/Rewrite\/main/raw.githubusercontent\.com\/axtyet\/iios\/main\/QuantumultX\/Chxm1023\/Rewrite/g' "$file"
            else
              echo "$file not found."
            fi
          done
          # 修改脚本链接
      - name: Edit iios/QuantumultX/Yu9191/Rewrite
        run: |
        cd iios-repo/QuantumultX/Yu9191/Rewrite
        for file in *.js; do
            if [ "$file" ] ; then
              sed -i 's/raw\.githubusercontent.com\/Yu9191\/Rewrite\/main/raw.githubusercontent\.com\/axtyet\/iios\/main\/QuantumultX\/Yu9191\/Rewrite/g' "$file"
            else
              echo "$file not found."
            fi
          done
          # 修改脚本链接
      - name: Edit iios/QuantumultX/Yu9191/rewrite/itunes
        run: |
        cd iios-repo/QuantumultX/Yu9191/Rewrite/itunes
        for file in *.js; do
            if [ "$file" ] ; then
              sed -i 's/raw\.githubusercontent.com\/chxm1023\/Rewrite\/main\/itunes/raw.githubusercontent\.com\/axtyet\/iios\/main\/QuantumultX\/Yu9191\/Rewrite\/itunes/g' "$file"
            else
              echo "$file not found."
            fi
          done


        # 循环结束后删除tmpfile
        rm tmpfile

    - name: Add and Commits
      run: |
        cd Tool-repo
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Surge/* Clash/* QuantumultX/* Loon/* Shadowrocket/* Stash/* Egern/* GeoIP/*
          git commit -m "Auto Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
          git push origin HEAD
        else
          echo "No changes to commit."
        fi

    - name: Cleanup Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2